language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      
sudo: required
dist: xenial

services:
    - mongodb

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_install:
  - sudo add-apt-repository -y ppa:jonathonf/ffmpeg-4
  - sudo apt-get update
  - sudo apt-get install -y ffmpeg

install:
    - pip install .[dev]

script:
    - tox
